name: flutterstarterkit
description: A feature ready start point for flexible & scalable flutter apps.
version: 0.8.5

publish_to: 'none' # Prevents the package from being publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  shared_preferences: ^2.0.4 # Persistent storage for simple data.
  permission_handler: ^6.1.0 # Add Support to request permissions and check their current status.
  provider: ^5.0.0 # Google Official Plugin for State Managment.
  package_info: ^2.0.0 # Provides information about the application package.

  cupertino_icons: ^1.0.2 # CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:

flutter:

  uses-material-design: true # Material Icons for Android style icons.

  assets:
    
  # App Image Folder
    - assets/images/

  # App Font Folder
    - assets/fonts/

  # Font Definition
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
          style: normal