name: flutterstarterkit
description: A feature ready start point for flexible & scalable flutter apps.
version: 0.8.0

publish_to: 'none' # Prevents the package from being publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2 # CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true # Material Icons for Android style icons.
